POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZTIuY29tIiwiZXhwIjoxNzMzMzU5ODA3LCJ1c2VySWQiOjN9.LvMRyotp5QodDN93W78FNmmz4SpG2X0fzTFdRcRlIC0

{
  "title": "Test Event From User",
  "description": "Test",
  "location": "Test Location",
  "organizer": "Test Organizer",
  "datetime": "2024-12-06T06:00:00.000Z"
}